apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keydb.fullname" . }}-health
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keydb.labels" . | nindent 4 }}
data:
  ping_readiness_local.sh: |-
    #!/bin/bash
    set -e
    [[ -n "${KEYDB_PASSWORD}" ]] && export REDISCLI_AUTH="${KEYDB_PASSWORD}"
    response="$(
      timeout -s 3 "${1}" \
      keydb-cli -h localhost -p {{ .Values.port }} PING
    )"
    if [ "${response}" = "LOADING KeyDB is loading the dataset in memory" ]; then
      echo "${response}"
      exit 1
    fi

  ping_liveness_local.sh: |-
    #!/bin/bash
    set -e
    [[ -n "${KEYDB_PASSWORD}" ]] && export REDISCLI_AUTH="${KEYDB_PASSWORD}"
    response="$(
      timeout -s 3 "${1}" \
      keydb-cli -h localhost -p {{ .Values.port }} PING
    )"
    if [ "${response}" != "PONG" ] && [ "${response}" != "LOADING KeyDB is loading the dataset in memory" ]; then
      echo "${response}"
      exit 1
    fi
