apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keydb.fullname" . }}-health
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keydb.labels" . | nindent 4 }}
data:
  ping_readiness_local.sh: |-
    #!/bin/bash
    response=$(
      timeout -s 3 $1 \
      keydb-cli \
        -h localhost \
        {{- if .Values.password }}
        -a "$KEYDB_PASSWORD" \
        {{- end }}
        -p 6379 \
        ping
    )
    if [ "$response" != "PONG" ]; then
      echo "$response"
      exit 1
    fi
  ping_liveness_local.sh: |-
    #!/bin/bash
    response=$(
      timeout -s 3 $1 \
      keydb-cli \
        -h localhost \
        {{- if .Values.password }}
        -a "$KEYDB_PASSWORD" \
        {{- end }}
        -p 6379 \
        ping
    )
    if [ "$response" != "PONG" ] && [ "$response" != "LOADING KeyDB is loading the dataset in memory" ]; then
      echo "$response"
      exit 1
    fi

