{{- if .Values.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keydb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keydb.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.password | b64enc | quote }}
{{- end }}

