{{- if and .Values.exporter.enabled .Values.exporter.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "keydb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keydb.labels" . | nindent 4 }}
  {{- with .Values.exporter.serviceMonitor.selector }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.exporter.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "keydb.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  - port: redis-exporter
    {{- if .Values.exporter.serviceMonitor.interval }}
    interval: {{ .Values.exporter.serviceMonitor.interval }}
    {{- end }}
    {{- if .Values.exporter.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.exporter.serviceMonitor.scrapeTimeout }}
    {{- end }}
{{- end }}

