apiVersion: v1
kind: Service
metadata:
  name: {{ include "keydb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keydb.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: keydb
    port: {{ .Values.port | int }}
    protocol: TCP
    targetPort: keydb
    {{- if .Values.service.appProtocol.enabled }}
    appProtocol: redis
    {{- end }}
  {{- if .Values.exporter.enabled }}
  - name: redis-exporter
    port: {{ .Values.exporter.port | int }}
    protocol: TCP
    targetPort: redis-exporter
    {{- if .Values.service.appProtocol.enabled }}
    appProtocol: http
    {{- end }}
  {{- end }}
  selector:
    {{- include "keydb.selectorLabels" . | nindent 4 }}
  sessionAffinity: ClientIP
